/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minesweeper;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import minesweeper.model.Board;

public class App extends Application {
    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        //launch();
        
        Board board = new Board();
        board.setMinesInitial(2);

        System.out.println(board);

        System.out.println("Clicking 5,5");

        board.clickOnSquare(5,5);

        System.out.println(board);

        System.out.println("Hrup");
    }
}
